
package com.tmp.services.hello;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWS", targetNamespace = "http://www.tmp.com/services/hello")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.tmp.services.hello.Weather>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://www.tmp.com/services/hello", className = "com.tmp.services.hello.QueryWeather")
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://www.tmp.com/services/hello", className = "com.tmp.services.hello.QueryWeatherResponse")
    public List<Weather> queryWeather(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
